name: dockerhub-readme

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/dockerhub-readme.yml'
      - 'docs/dockerhub.md'

env:
  DOCKERHUB_SLUG: distribution/distribution

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      -
        name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_SLUG }}
          readme-filepath: ./docs/dockerhub.md
